theme: jekyll-theme-cayman
title: French Verb Learning
description: Simple steps to perfecting French verbs
github:
  page2: tutorial2.html
  page3: listening.html
  page4: verbconjugations.html
  page5: page5.html
