theme: jekyll-theme-cayman
title: Guide to French Verbs
description: Simple steps to perfecting French verbs
github:
  page2: introduction.html
  page3: listening.html
  page4: tenses.html
  page5: reading-and-writing.html
