theme: jekyll-theme-cayman
title: Learn French Today
description: Simple steps to perfect French
github:
  page2: tutorial2.html
  page3: listening.html
  page4: verbconjugations.html
  page5: page5.html
